# Matrix Multiplication Simulation

Ref:

  * Markov Chains: Simulation in Python | Stationary Distribution Computation | Part - 7 | Normalized Nerd
  * Monte Carlo Simulation with Card Games | Normalized Nerd
  * The Central Limit Theorem Clearly Explained! | Normalized Nerd
  * Law of large numbers | Probability and Statistics | Khan Academy

Import the following library tools

In [ ]:
import numpy as np

Create a transition matrix to show the probabilities of transitioning between the markov states

In [ ]:
A = np.array([[0.2, 0.6, 0.2], [0.3, 0.0, 0.7], [0.5, 0.0, 0.5]])

Draft up a function for multiplying matricies multiple times in order to estimate the probability distribution of the three states (represented by the variable pi)

Show code in non-function format since juypter is truncating the function window when saving as pdf

In [6]:
steps = 10**3
A_m = A

i = 0
while i < steps:
  A_m = np.matmul(A_m, A)
  i+= 1

print("A^m = \n", A_m, "\n")
print("pi = ", A_m[0])

A^m = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

pi =  [0.35211268 0.21126761 0.43661972]


Numpy
> https://numpy.org/doc/stable/